#!/stage1/busybox sh

####################################
#  SH KOR Galaxy S Series Project  #
#  Hoppin, CM9 ICS                 #
#  By Sunghun.Ra                   #
#     http://theteamdev.com        #
####################################

export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox mount -t yaffs2 /dev/block/mtdblock2 /system
busybox mount -t yaffs2 /dev/block/mtdblock3 /cache

RAMDISK=ramdisk.cpio.gz

##### *SH* We'll boot recovery for Key input

if busybox test -e /cache/.startrecovery ; then
	# recovery boot
	RAMDISK=ramdisk-recovery.cpio.gz
	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

elif ! busybox test -e /system/build.prop ; then
	# emergency boot
        busybox umount /cache
        erase_image cache
        busybox mount -t yaffs2 /dev/block/mtdblock3 /cache
        busybox mkdir /cache/recovery
	busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard	

	# UPDATE=$(busybox cat /sdcard/cyanogenmod.cfg)
	# if busybox test -e $UPDATE ; then
	# 	busybox echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
  	# fi
	
	RAMDISK=ramdisk-recovery.cpio.gz
	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

busybox umount /cache
busybox umount /system
busybox umount /sdcard
busybox rmdir /sdcard

busybox gunzip -c ${RAMDISK} | busybox cpio -i

if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	busybox cp lpm.rc init.rc
	busybox rm init.SHW-M190S.rc
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr ramdisk.cpio.gz
busybox rm -fr ramdisk-recovery.cpio.gz
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
